### ISSUE TITLE
About CIHP_PGN

### ISSUE THREAD

**Issue by LogWell** [rcrvano/moikrug.parser#1]
Hi, can you run the CIHP_PGN code now?

**Comment by LogWell** [comment]
I found a way to run it. I don't know if it's correct. Welcome to discuss.

Using `tool/write_edge.m` to generate edges, modify them appropriately, maybe you should create a `img_list.txt` in `list`, and then copy the generated edges directly to `labels`, and run it.

**Comment by rcrvano** [comment]
Hum. And this way worked for you?

**Comment by LogWell** [comment]
Yes, have a try~

**Comment by rcrvano** [comment]
Can you tell me please how you are compiled write_edge.m and reverse_label.m and how you are run it?

**Comment by LogWell** [comment]
It's a matlab file, I use `write_edge.m` only to generate `edges`, then copy to `labels` and you are ready to run.

**Comment by LogWell** [comment]
liks this:

```
clear;
close all;
fclose all;
%%
imglist = '../list/img_list.txt';  % 00000.png
list = textread(imglist, '%s');

for i = 1:length(list);
    imname = list{i};
    instance_map = imread(fullfile('../images', imname));
    instance_contour = uint8(imgradient(rgb2gray(instance_map)) > 0);
    imwrite(instance_contour, fullfile('../edges', imname));
end
```

**Comment by rcrvano** [comment]
Thanks a lot! I will try!

**Comment by h-bo** [comment]
Does it work?

**Comment by rcrvano** [comment]
I will try a little later (I hope on monday). And I will let you know

**Comment by h-bo** [comment]
@LogWell Have you reproduced result for PGN?  I tried, but failed with bad edges.

**Comment by LogWell** [comment]
![](https://raw.githubusercontent.com/LogWell/Markdown/master/20190525_141134.png)

**Comment by LogWell** [comment]
Look at the code, try it several times, it will succeed.

**Comment by rcrvano** [comment]
It works fine! Thank you very much for your help! :)
